eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
#  instance:
#    hostname: clientName
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sprintcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8081